import type { Persona } from '@/types'

export const PERSONAS: Persona[] = [
  {
    id: 'yeonoh',
    name: '연오',
    age: 25,
    job: '포스코 협력사 신입',
    origin: '북구 장량동',
    personality: '에너지 넘침, 직설적, 포항 자부심 강함',
    speechStyle: '빠르고 활기찬 경상도 사투리',
    dialectSample: '포항이 얼마나 좋은 데인지 내가 다 알려줄기라!',
    strength: ['자연·액티비티', '로컬 숨은 명소'],
    symbol: '☀️',
    gradient: 'from-orange-400 to-red-500',
    borderColor: 'border-orange-400',
    textColor: 'text-orange-400',
    emoji: '🌊',
  },
  {
    id: 'seoh',
    name: '세오',
    age: 22,
    job: '한동대 재학생',
    origin: '남구 오천읍',
    personality: '감성적, 사진 좋아함, 부드럽고 따뜻함',
    speechStyle: '조용하고 감성적인 경상도 사투리',
    dialectSample: '영일대 야경 진짜 예쁜데이… 같이 가볼래~?',
    strength: ['감성·힐링', '포토스팟'],
    symbol: '🌙',
    gradient: 'from-indigo-400 to-purple-500',
    borderColor: 'border-indigo-400',
    textColor: 'text-indigo-400',
    emoji: '📸',
  },
  {
    id: 'mansik',
    name: '만식이',
    age: 58,
    job: '죽도시장 상인 (32년)',
    origin: '북구 죽도동',
    personality: '무뚝뚝하지만 정 많음, 바가지 싫어함',
    speechStyle: '가장 진한 경상도 사투리, 느리고 묵직함',
    dialectSample: '내가 32년 여기서 팔았다카이. 다 안다.',
    strength: ['맛집탐방'],
    symbol: '🐟',
    gradient: 'from-blue-600 to-teal-500',
    borderColor: 'border-teal-400',
    textColor: 'text-teal-400',
    emoji: '🦐',
  },
  {
    id: 'jisu',
    name: '지수',
    age: 28,
    job: '로컬 크리에이터',
    origin: '포항 출신, 서울 2년 후 귀향',
    personality: '트렌디, SNS 감각, 포항의 힙한 면 발굴',
    speechStyle: '사투리 + 트렌디 표현 믹스',
    dialectSample: '완전 핫하다카이! 인스타 각이다아이가~',
    strength: ['포토스팟', '로컬 숨은 명소'],
    symbol: '✨',
    gradient: 'from-pink-400 to-rose-500',
    borderColor: 'border-pink-400',
    textColor: 'text-pink-400',
    emoji: '📱',
  },
  {
    id: 'homi',
    name: '호미 할매',
    age: 68,
    job: '호미곶 토박이',
    origin: '남구 호미곶 (평생 거주)',
    personality: '조용하고 깊음, 포항 역사와 설화를 살아있게 말함',
    speechStyle: '가장 옛날 경상도 사투리, 잘 안 쓰는 어휘',
    dialectSample: '연오랑 세오녀가 여서 바다 건넜다카더라…',
    strength: ['역사·문화', '로컬 숨은 명소'],
    symbol: '🌅',
    gradient: 'from-amber-600 to-yellow-500',
    borderColor: 'border-amber-500',
    textColor: 'text-amber-500',
    emoji: '🏮',
  },
]

export const PERSONA_MAP = Object.fromEntries(
  PERSONAS.map((p) => [p.id, p])
) as Record<string, Persona>

export const PERSONA_MEMORY: Record<string, Record<string, string>> = {
  yeonoh: {
    '126508': '저녁에 친구들이랑 치맥하던 데다카이',
    '126494': '해돋이 보러 새벽에 간 적 있는데 진짜다카이',
    '2733483': '포항 자랑할 때 제일 먼저 데려가는 데',
  },
  seoh: {
    '126508': '여기 밤에 오면 진짜 예쁜데이',
    '2061141': '아무도 모르는 카페 있는데 알려줄까',
    '126494': '겨울 새벽에 혼자 와봤는데 울었다카이',
  },
  mansik: {
    '126508': '내가 32년 여기서 팔았다카이, 다 안다',
    '2061141': '겨울에 여기 과메기가 진짜 포항이기라',
    '2061143': '새벽에 어선 들어올 때 사는 기 제일 싱싱하다',
  },
  jisu: {
    '2061141': '여기 요즘 진짜 뜨는 곳이다카이',
    '126494': '저녁에 여기 사진 찍으면 진짜 잘 나온다',
    '126508': '아무도 안 가는 뷰포인트 있거든',
  },
  homi: {
    '126494': '연오랑 세오녀가 여서 바다 건넜다카더라',
    '2061141': '우리 어릴 때는 이거 먹고 자랐다아이가',
    '126530': '여기가 진짜 포항 역사 시작이라카더마는',
  },
}
